### ISSUE TITLE
Fix versioning and package id

### ISSUE THREAD

**Issue by krt16s** [mdecorde/BAC76#3]
Your `build.gradle` says this is...

````
        versionCode 1
        versionName "1.0"
````

.... however your tags say oherwise. So I'd suspect this should be versionCode 3 and versioName 0.3 instead.

Second, you changed the package id. The package id is a unique identifier, if you change it, it is a nother app with NO WAY to upgrade existing users. You don't change it, ever... you even stick with it when you made a typo. The only reason to change it, is because of the mayor appstore out there bullies you to do it. Even then it breaks fundamentally with Androids architecture...

**Comment by mdecorde** [comment]
yeah sorry I'm not used to the gradle files. I've fix the version and package name it contains : https://github.com/mdecorde/BAC76/commit/9bdf127c0d2d8edc7be73b664e2cabb5491cbaf4

thx you for your help

**Comment by ghost** [comment]
Thanks for the quick reply, https://gitlab.com/fdroid/fdroiddata/commit/45855a0f68dcfe2ba23759fbb20f9e938aa99303 should fix this on our side.
